<?php

namespace LaFuente\Bundle\PrestamosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoProductoRepository extends EntityRepository
{
}
