<?php

namespace LaFuente\Bundle\PrestamosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getAllAvailables($state=true){
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.availability = :en')
            ->setParameter('en', $state);
    }
}
