<?php

namespace LaFuente\Bundle\PrestamosBundle\Entity;

/**
 * TermoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermoRepository extends ProductRepository
{
}
